import { NextResponse } from 'next/server'
import { Resend } from 'resend'
import { getAuthContext, authErrorResponse } from '@/lib/auth'

const resend = new Resend(process.env.RESEND_API_KEY)

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

export async function POST(req: Request) {
  try {
    const { supabase, businessId } = await getAuthContext()

    let vendorEmail: string, vendorName: string | undefined, orderText: string, businessName: string | undefined
    try {
      ;({ vendorEmail, vendorName, orderText, businessName } = await req.json())
    } catch {
      return NextResponse.json({ error: 'Invalid request body' }, { status: 400 })
    }

    if (!vendorEmail || !orderText) {
      return NextResponse.json({ error: 'Missing vendor email or order text' }, { status: 400 })
    }

    if (!EMAIL_RE.test(vendorEmail)) {
      return NextResponse.json({ error: 'Invalid vendor email address' }, { status: 400 })
    }

    // Get business contact email to CC the owner
    const { data: biz } = await supabase
      .from('businesses')
      .select('contact_email')
      .eq('id', businessId)
      .single()

    const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

    const html = `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #1e293b;">
      <p style="color: #64748b; font-size: 14px; margin-bottom: 24px;">${today}</p>
      <p>Hi ${vendorName},</p>
      <p>Please find our purchase order below:</p>
      <pre style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; font-family: monospace; font-size: 13px; white-space: pre-wrap; color: #334155;">${orderText}</pre>
      <p style="color: #64748b; font-size: 13px; margin-top: 32px;">This order was generated by <a href="https://barguard.app" style="color: #f59e0b;">BarGuard</a>.</p>
    </div>
  `

    const { error } = await resend.emails.send({
      from: 'BarGuard <support@barguard.app>',
      to: vendorEmail,
      ...(biz?.contact_email ? { cc: biz.contact_email } : {}),
      subject: `Purchase Order from ${businessName || 'My Bar'} — ${today}`,
      html,
    })

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ success: true })
  } catch (e) { return authErrorResponse(e) }
}
